test the deliberately failing tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,3 +16,12 @@ jobs:
           repository-cache: true
       - run: |
           bazel test ...
+          # These two tests fail, deliberately, so fail if they pass 
+          if bazel test //fixtures:fixture2_unused_deps_test
+          then
+            exit 1
+          fi
+          if bazel test //fixtures:fixture3_uber_unused_deps_test
+          then
+            exit 1
+          fi
